// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417191914_start")]
    partial class start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 17, 19, 19, 13, 233, DateTimeKind.Utc).AddTicks(5460),
                            PasswordHash = "$2a$11$xwlNs416ilRBB6ym7YjwQuEAzIRYXQR02pvJmPm9V8aG4BhrKJBKO",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 4, 17, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(2932),
                            PasswordHash = "$2a$11$cRcBmRPTP8MzKY2NI6.jP.9vyYEMilDgHuqBgvOGtxOCqooc3Xhpu",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 18, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4039),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "amiat.sharma31@example.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2025, 12, 18, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4028),
                            LastName = "Sharma",
                            Phone = "9876543210",
                            Salary = 60000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 18, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4040)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 29, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4045),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "pribya.mehta32@example.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2025, 9, 29, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4044),
                            LastName = "Mehta",
                            Phone = "9123456780",
                            Salary = 55000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 9, 29, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4046)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4058),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "rcahul.verma33@example.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2026, 1, 17, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4050),
                            LastName = "Verma",
                            Phone = "9988776655",
                            Salary = 50000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 1, 17, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4059)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 16, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4063),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "nehda.kapoor34@example.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2026, 2, 16, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4062),
                            LastName = "Kapoor",
                            Phone = "9090909090",
                            Salary = 45000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 16, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4064)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 21, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4164),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "sueresh.patil35@example.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2025, 6, 21, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4163),
                            LastName = "Patil",
                            Phone = "8888888888",
                            Salary = 70000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 6, 21, 19, 19, 13, 423, DateTimeKind.Utc).AddTicks(4164)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "amfit.sharma36@example.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sharma",
                            Phone = "9876543210",
                            Salary = 60000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "prgiya.verma37@example.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Verma",
                            Phone = "9876543211",
                            Salary = 45000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "rahhul.kumar38@example.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kuhmar",
                            Phone = "9876543212",
                            Salary = 70000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "snehia.patil39@example.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patil",
                            Phone = "9876543213",
                            Salary = 52000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "vikrjam.singh40@example.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Singh",
                            Phone = "9876543214",
                            Salary = 80000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Backend Developer",
                            Email = "nehka.gupta41@example.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gupta",
                            Phone = "9876543215",
                            Salary = 65000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Frontend Developer",
                            Email = "arljun.mehta42@example.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mehta",
                            Phone = "9876543216",
                            Salary = 62000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "SEO Analyst",
                            Email = "kavmya.nair43@example.com",
                            FirstName = "Kavya",
                            JoinDate = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nair",
                            Phone = "9876543217",
                            Salary = 48000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Designation = "Recruiter",
                            Email = "ronhit.yadav44@example.com",
                            FirstName = "Rohit",
                            JoinDate = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yadav",
                            Phone = "9876543218",
                            Salary = 43000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "anjoali.deshmukh45@example.com",
                            FirstName = "Anjali",
                            JoinDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Deshmukh",
                            Phone = "9876543219",
                            Salary = 55000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
